### ISSUE TITLE
Front LED stays green after usb disk ejection

### ISSUE THREAD

**Issue by nnachtegael** [schmidhorst/synology-autorun#4]
I'm working with a DS223 DSM 7.2 (latest version)
and here is my config
LED_COPY="5"
WAIT="5"
LED_STATUS="3"
NOTIFY_USERS="@users"
SCRIPT_AFTER_EJECT=""
TRIES="40"
ADD_NEW_FINGERPRINTS="0"
LOGLEVEL="5"
LOG_MAX_LINES="2000"
EJECT_RETURN_CODES="100"
SCRIPT="/volume1/system/scripts/my-autorun.cmd"
EJECT_TIMEOUT="300"
FAILURE_CODES=""
CAPTURE="0"
NO_DSM_MESSAGE_RETURN_CODES=""
BEEP="false

All things are OK: LED becomes green and flashing when my script is executed but
the front LED stays green after usb eject (eject from upper right corner desktop screen)

how can I eject my USB disk so that the front LED goes OFF ?

**Comment by schmidhorst** [comment]
Hello nnachtegael,

 

with which return code is your script returning to AUTORUN at its exit?

Is it the code 100, for which the automated eject is setup?
                EJECT_RETURN_CODES="100"

 

If I am understanding you correct, you don’t have that return code and you are using manual ejecting.

 

There is actual no notification to AUTORUN from such a manual eject action implemented! That would be an additional feature to be implemented in a future version.

 

The process, which was started at insertion of the USB drive is terminating shortly after your script /volume1/system/scripts/my-autorun.cmd  is finished.

The last LED change by the actual AUTORUN version can be done when the script is finished before it’s terminating.

 

 

Best Regards

Horst

 

 

PS:

Some Info about controlling the LEDs can be found here:

https://community.synology.com/enu/forum/17/post/74526 

https://www.synology-forum.de/threads/leds-ausschalten-oder-runterdimmen.30013/post-247250 

 

LED control requires always root permission.

synoexternal -susled disk_green | disk_orange | power none | steady | blink

echo \8 \4 \B> /dev/ttyS1

printf  "\\x35" > /dev/ttyS1

 

1             0x31      DSM power off

2             0x32      short beep

3             0x33      long beep

4             0x34      Power LED on

5             0x35      Power LED flashing

6             0x36      Power LED off

7             0x37      Status LED off

8             0x38      Status LED green

9             0x39      Status LED grün flashing

:              0x3A      Status LED orange on

;              0x3B      Status LED orange flashing

@           0x40      Copy LED on

A             0x41      Copy LED flashing

B             0x42      Copy LED off

 

Von: nnachtegael ***@***.***> 
Gesendet: Mittwoch, 6. Dezember 2023 17:31
An: schmidhorst/synology-autorun ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [schmidhorst/synology-autorun] Front LED stays green after usb disk ejection (Issue #4)

 

I'm working with a DS223 DSM 7.2 (latest version)
and here is my config
LED_COPY="5"
WAIT="5"
LED_STATUS="3"
***@***.***"
SCRIPT_AFTER_EJECT=""
TRIES="40"
ADD_NEW_FINGERPRINTS="0"
LOGLEVEL="5"
LOG_MAX_LINES="2000"
EJECT_RETURN_CODES="100"
SCRIPT="/volume1/system/scripts/my-autorun.cmd"
EJECT_TIMEOUT="300"
FAILURE_CODES=""
CAPTURE="0"
NO_DSM_MESSAGE_RETURN_CODES=""
BEEP="false

All things are OK: LED becomes green and flashing when my script is executed but
the front LED stays green after usb eject (eject from upper right corner desktop screen)

how can I eject my USB disk so that the front LED goes OFF ?

**Comment by nnachtegael** [comment]
Thank you
Things are now working as expected with a 'exit 100' at the end of my script
